### ISSUE TITLE
Rename to fish-plugin

### ISSUE THREAD

**Issue by jorgebucaran** [andreiborisov/fish-package#1]
For consistency across the ecosystem and Fisher's documentation.

**Comment by andreiborisov** [comment]
@jorgebucaran a link from Fisher README perhaps can be useful for new users and would be greatly appreciated🙏

**Comment by jorgebucaran** [comment]
Want to add this to https://git.io/awsm.fish too?

**Comment by andreiborisov** [comment]
@jorgebucaran I think it's more useful for Fisher plugin devs so it would be more appropriate in Fisher README (as a continuation of `Creating a plugin` section), awesome lists, at least in my mind, are more about actual projects/plugins, but it's your call.

I would love to make a PR for adding my Docker images repo in the awesome list though🤗
